# Generated by Django 6.1 on 2026-09-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_alter_wallet_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='type',
            field=models.CharField(choices=[('checking', 'Conta corrente'), ('savings', 'Poupança'), ('credit_card', 'Cartão de crédito'), ('cash', 'Dinheiro'), ('benefit', 'Vale/Benefício')], default='checking', max_length=20),
        ),
    ]
