# Generated by Django 6.1 on 2026-09-04 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('income', 'Receita'), ('expense', 'Despesa'), ('transfer', 'Transferência')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField()),
                ('is_recurring', models.BooleanField(default=False)),
                ('ai_category_confidence', models.FloatField(blank=True, help_text='Confiança (0-1) da categorização automática, quando aplicável.', null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='categories.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='transactions', to='categories.tag')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallets.wallet')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['wallet', 'date'], name='transaction_wallet__744cbd_idx'), models.Index(fields=['category', 'date'], name='transaction_categor_720c85_idx')],
            },
        ),
    ]
