# Generated by Django 6.1 on 2026-09-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='down_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor de entrada, se a meta for financiar o restante do valor total (opcional). Quando preenchido, o progresso e o quanto guardar por mês passam a ser calculados sobre esse valor, não sobre target_amount.', max_digits=12, null=True),
        ),
    ]
