# Generated by Django 6.1 on 2026-09-05 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Informativo'), ('warning', 'Atenção'), ('critical', 'Crítico')], max_length=10)),
                ('data_snapshot', models.JSONField(blank=True, default=dict, help_text='Dados brutos que geraram o insight — auditoria/debug.')),
                ('is_read', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
